server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
#    url: jdbc:h2:file:~/test
#    driverClassName: org.h2.Driver
#    data: classpath:test-setup.sql #test-setup.sql can be put in resources folder
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  file:
    path: .
    
api:
  key: ${NEWS_API_KEY}