server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
#    url: jdbc:h2:file:~/test
#    driverClassName: org.h2.Driver
#    data: classpath:test-setup.sql #test-setup.sql can be put in resources folder
    url: jdbc:postgresql://training-db.cqnsz9u6mm7d.us-east-2.rds.amazonaws.com:5432/postgres?currentSchema=project-2
    username: postgres
    password: pa55word
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  file:
    path: .

#This is a test
#server:
#  port: 8082
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#spring:
#  datasource:
##    url: jdbc:postgresql://database-1.cs1tymkociae.us-east-2.rds.amazonaws.com:5432/postgres
##    username: postgres
##    password: anderson
#    url: {{SPRING_DATASOURCE_URL}}
#    username: {{SPRING_DATASOURCE_USERNAME}}
#    password: {{SPRING_DATASOURCE_PASSWORD}}
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#    jackson:
#      serialization:
#        fail-on-empty-beans: false
