server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
#    url: jdbc:postgresql://database-1.cs1tymkociae.us-east-2.rds.amazonaws.com:5432/postgres
#    username: postgres
#    password: anderson

    url: jdbc:postgresql://training-db.cvaaoud1no8t.us-east-2.rds.amazonaws.com:5432/postgres?currentSchema=project3
    username: postgres
    password: 12345678

  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    jackson:
      serialization:
        fail-on-empty-beans: false